import {
  generateTemplate,
  stripValues,
  formatTemplateResult,
} from "./envTemplate";

const sampleEnv = {
  DB_HOST: "localhost",
  DB_PORT: "5432",
  APP_NAME: "myapp",
  APP_ENV: "production",
  SECRET_KEY: "abc123",
};

describe("generateTemplate", () => {
  it("generates a flat template with empty values", () => {
    const result = generateTemplate(sampleEnv);
    expect(result.keys).toHaveLength(5);
    expect(result.content).toContain("DB_HOST=");
    expect(result.content).not.toContain("localhost");
    expect(result.groupCount).toBe(1);
  });

  it("uses custom placeholder", () => {
    const result = generateTemplate(sampleEnv, { placeholder: "CHANGEME" });
    expect(result.content).toContain("DB_HOST=CHANGEME");
  });

  it("includes comments by default", () => {
    const result = generateTemplate(sampleEnv);
    expect(result.content).toContain("# Generated by envoy-cli");
  });

  it("excludes comments when disabled", () => {
    const result = generateTemplate(sampleEnv, { includeComments: false });
    expect(result.content).not.toContain("#");
  });

  it("groups keys by prefix", () => {
    const result = generateTemplate(sampleEnv, { groupByPrefix: true });
    expect(result.groupCount).toBe(3);
    expect(result.content).toContain("# DB settings");
    expect(result.content).toContain("# APP settings");
  });

  it("handles empty env", () => {
    const result = generateTemplate({});
    expect(result.keys).toHaveLength(0);
    expect(result.groupCount).toBe(1);
  });
});

describe("stripValues", () => {
  it("strips all values to empty strings", () => {
    const result = stripValues(sampleEnv);
    expect(Object.values(result).every((v) => v === "")).toBe(true);
    expect(Object.keys(result)).toEqual(Object.keys(sampleEnv));
  });
});

describe("formatTemplateResult", () => {
  it("formats single group result", () => {
    const result = generateTemplate(sampleEnv);
    const msg = formatTemplateResult(result);
    expect(msg).toContain("5 key(s)");
  });

  it("formats multi-group result", () => {
    const result = generateTemplate(sampleEnv, { groupByPrefix: true });
    const msg = formatTemplateResult(result);
    expect(msg).toContain("3 group(s)");
  });
});
