export interface TemplateOptions {
  placeholder?: string;
  includeComments?: boolean;
  groupByPrefix?: boolean;
}

export interface TemplateResult {
  content: string;
  keys: string[];
  groupCount: number;
}

const DEFAULT_PLACEHOLDER = "";

export function generateTemplate(
  env: Record<string, string>,
  options: TemplateOptions = {}
): TemplateResult {
  const {
    placeholder = DEFAULT_PLACEHOLDER,
    includeComments = true,
    groupByPrefix = false,
  } = options;

  const keys = Object.keys(env);

  if (groupByPrefix) {
    return generateGroupedTemplate(keys, placeholder, includeComments);
  }

  const lines: string[] = [];
  if (includeComments) {
    lines.push("# Generated by envoy-cli");
    lines.push("# Fill in the values below");
    lines.push("");
  }

  for (const key of keys) {
    lines.push(`${key}=${placeholder}`);
  }

  return {
    content: lines.join("\n"),
    keys,
    groupCount: 1,
  };
}

function generateGroupedTemplate(
  keys: string[],
  placeholder: string,
  includeComments: boolean
): TemplateResult {
  const groups = new Map<string, string[]>();

  for (const key of keys) {
    const prefix = key.includes("_") ? key.split("_")[0] : "OTHER";
    if (!groups.has(prefix)) groups.set(prefix, []);
    groups.get(prefix)!.push(key);
  }

  const lines: string[] = [];
  if (includeComments) {
    lines.push("# Generated by envoy-cli");
    lines.push("");
  }

  for (const [prefix, groupKeys] of groups) {
    if (includeComments) {
      lines.push(`# ${prefix} settings`);
    }
    for (const key of groupKeys) {
      lines.push(`${key}=${placeholder}`);
    }
    lines.push("");
  }

  return {
    content: lines.join("\n").trimEnd(),
    keys,
    groupCount: groups.size,
  };
}

export function stripValues(
  env: Record<string, string>
): Record<string, string> {
  return Object.fromEntries(Object.keys(env).map((key) => [key, ""]));
}

export function formatTemplateResult(result: TemplateResult): string {
  return [
    `Generated template with ${result.keys.length} key(s)`,
    result.groupCount > 1 ? ` across ${result.groupCount} group(s)` : "",
  ]
    .join("")
    .trim();
}
